### PR TITLE
Adding support for Elliptic Curve DSA keys

### PR DESCRIPTION
**Pull request by evenaglia**

### CODE REVIEW

**Comment by jeanouii** [comment]
Hello,

Would you be able to add a test case or 2?
Even an happy path test case would be good.

Thanks
Jean-Louis

**Comment by jeanouii** [comment]
Thank you very much.
It's ready to go.

**Comment by evenaglia** [comment]
When will you release 1.1?

I don't see a history for your release schedule thus far, and there was mention of a release [10 months ago](https://github.com/tomitribe/http-signatures-java/issues/7) but it seems that it never happened.

**Comment by evenaglia** [comment]
I now see [1.1 in the maven repository](https://mvnrepository.com/artifact/org.tomitribe/tomitribe-http-signatures/1.1). Many thanks for your prompt service!

**Pull request merged**
